### ISSUE TITLE
client.Discover: Issuer matching is too strict

### ISSUE THREAD

**Issue by kostyay** [caos/oidc#122] opened 2021-09-02 09:38 UTC
**Describe the bug**
Currently `client.Discover` will fail if the provided `issuer` doesn't match the returned `issuer`. However this validation is too strict as it will fail with `oidc.ErrIssuerInvalid` even if i provide `https://my.oidc.com` in the function parameter but the returned value will be `https://my.oidc.com/` (real use case I encountered).

**Expected behavior**
I expect discover to succeed if the returned issuer "starts with" the provided issuer or have an option to disable this verification.

**Comment by livio-a** [comment] 2021-09-03 05:14
Hi @kostyay 

Thanks for reaching out.

I get your problem, but IMO loosen the validation won't solve it or just relocate it to somewhere else (e.g. token validation).

The problem is, that it's the OpenID Provider's choice whether its `issuer` has a trailing '/' or not. The Relaying Party will have to take over its decision.

[4.3 of OIDC Discovery](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation) requires to validate the issue to be identical:
> The issuer value returned MUST be identical to the Issuer URL that was directly used to retrieve the configuration information. This MUST also be identical to the iss Claim value in ID Tokens issued from this Issuer.

For Discovery, [OIDC also says](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest) to remove the trailing `/` **for the request** if an issuer has one:
> If the Issuer value contains a path component, any terminating / MUST be removed before appending /.well-known/openid-configuration.

So in your case, wouldn't it work if you would provide `https://my.oidc.com/` as issuer?

**Comment by fforootd** [comment] 2021-09-08 06:54
Hi @kostyay 

I am closing this issue for now 😁 

Feel free to reopen this issue if the need arises again.

**Closed by fforootd** 2021-09-08 06:54 UTC
Labels: bug
