### ISSUE TITLE
Starting an OP with an Issuer URL that contains a path breaks the endpoint handling

### ISSUE THREAD

**Issue by sebastiaopamplona** [caos/oidc#155] opened 2022-02-10 10:12 UTC
**Describe the bug**
Starting an OP with an Issuer URL that contains a path breaks the endpoint handling.

**To Reproduce**
1. Apply the following patch:
```diff
diff --git a/example/server/default/default.go b/example/server/default/default.go
index 7edaf2e..1877218 100644
--- a/example/server/default/default.go
+++ b/example/server/default/default.go
@@ -17,7 +17,7 @@ func main() {
 	ctx := context.Background()
 	port := "9998"
 	config := &op.Config{
-		Issuer:    "http://localhost:9998/",
+		Issuer:    "http://localhost:9998/path/to/my/op",
 		CryptoKey: sha256.Sum256([]byte("test")),
 	}
 	storage := mock.NewAuthStorage()
@@ -26,7 +26,7 @@ func main() {
 		log.Fatal(err)
 	}
 	router := handler.HttpHandler().(*mux.Router)
-	router.Methods("GET").Path("/login").HandlerFunc(HandleLogin)
+	router.Methods("GET").Path("/path/to/my/op/login").HandlerFunc(HandleLogin)
 	router.Methods("POST").Path("/login").HandlerFunc(HandleCallback)
 	server := &http.Server{
 		Addr:    ":" + port,
@@ -68,5 +68,5 @@ func HandleLogin(w http.ResponseWriter, r *http.Request) {
 func HandleCallback(w http.ResponseWriter, r *http.Request) {
 	r.ParseForm()
 	client := r.FormValue("client")
-	http.Redirect(w, r, "/authorize/callback?id="+client, http.StatusFound)
+	http.Redirect(w, r, "/path/to/my/op/authorize/callback?id="+client, http.StatusFound)
 }

```
2. Start example OP:
```bash
CAOS_OIDC_DEV=1 go run github.com/caos/oidc/example/server/default
```

**Expected behavior**
1. Now that I have my OP running on `http://localhost:9998/path/to/my/op`, I expect the Discovery Endpoint to be:
```bash
curl http://localhost:9998/path/to/my/op/.well-known/openid-configuration <- 404 Not Found
```
but instead it **does not contain the path of my Issuer URL**:
```bash
curl http://localhost:9998/.well-known/openid-configuration <- 200 OK
```
2. The endpoints in the Discovery Endpoint response are indeed correct, but **when I try to curl them I get 404 Not Found**:
```bash
curl http://localhost:9998/.well-known/openid-configuration | jq

{
  "issuer": "http://localhost:9998/path/to/my/op",
  "authorization_endpoint": "http://localhost:9998/path/to/my/op/authorize",
  "token_endpoint": "http://localhost:9998/path/to/my/op/test",
  "introspection_endpoint": "http://localhost:9998/path/to/my/op/oauth/introspect",
  "userinfo_endpoint": "http://localhost:9998/path/to/my/op/userinfo",
  "revocation_endpoint": "http://localhost:9998/path/to/my/op/revoke",
  "end_session_endpoint": "http://localhost:9998/path/to/my/op/end_session",
  "jwks_uri": "http://localhost:9998/path/to/my/op/keys",
  "scopes_supported": [
  (...)

curl http://localhost:9998/path/to/my/op/authorize <- 404 Not Found
```

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by livio-a** [comment] 2022-02-14 07:26
Hey @sebastiaopamplona 

Thank you for the issue as well as this PR. 

I could reproduce your problem. And as you wrote, the discovery endpoint is serving the correct endpoints.
The problem is, that the example server does not serve the http handler correctly for that case.
Changing the http handler of the op to be served on the correct path will solve this problem:
```diff
diff --git a/example/server/default/default.go b/example/server/default/default.go
index 7edaf2e..f48fbf9 100644
--- a/example/server/default/default.go
+++ b/example/server/default/default.go
@@ -17,7 +17,7 @@ func main() {
        ctx := context.Background()
        port := "9998"
        config := &op.Config{
-               Issuer:    "http://localhost:9998/",
+               Issuer:    "http://localhost:9998/path/test",
                CryptoKey: sha256.Sum256([]byte("test")),
        }
        storage := mock.NewAuthStorage()
@@ -25,7 +25,8 @@ func main() {
        if err != nil {
                log.Fatal(err)
        }
-       router := handler.HttpHandler().(*mux.Router)
+       router := mux.NewRouter()
+       router.PathPrefix("/path/test/").Handler(http.StripPrefix("/path/test", handler.HttpHandler()))
        router.Methods("GET").Path("/login").HandlerFunc(HandleLogin)
        router.Methods("POST").Path("/login").HandlerFunc(HandleCallback)
        server := &http.Server{
@@ -68,5 +69,5 @@ func HandleLogin(w http.ResponseWriter, r *http.Request) {
 func HandleCallback(w http.ResponseWriter, r *http.Request) {
        r.ParseForm()
        client := r.FormValue("client")
-       http.Redirect(w, r, "/authorize/callback?id="+client, http.StatusFound)
+       http.Redirect(w, r, "/path/test/authorize/callback?id="+client, http.StatusFound)
 }

```

The login will still be served directly on root, which is totally ok as it's not part of OIDC / the OP handler.
This will also make it easier if the OP is just a part of your whole application, where you have multiple other routes / handlers.

And the issuer path doesn't necessarily have to be the path the handler will be served on. In our IAM for example, the OP is currently started on a dedicated path internally (`/oauth/v2/`) and exposed on a custom domain (`issuer.zitadel.ch`) without any path through an external reverse proxy. The endpoints are also served through multiple domains:
https://issuer.zitadel.ch/.well-known/openid-configuration

```json
{
  "issuer": "https://issuer.zitadel.ch",
  "authorization_endpoint": "https://accounts.zitadel.ch/oauth/v2/authorize",
  "token_endpoint": "https://api.zitadel.ch/oauth/v2/token",
  "introspection_endpoint": "https://api.zitadel.ch/oauth/v2/introspect",
  "userinfo_endpoint": "https://api.zitadel.ch/oauth/v2/userinfo",
  "revocation_endpoint": "https://api.zitadel.ch/oauth/v2/revoke",
  "end_session_endpoint": "https://accounts.zitadel.ch/oauth/v2/endsession",
  "jwks_uri": "https://api.zitadel.ch/oauth/v2/keys",
  ...
}
```
The `accounts` domain handles all user (agent) facing requests including the login UI (which we internally serve on another path prefix: /login.


I'll try to find some time this week to update the server example (see also https://github.com/caos/oidc/issues/116 and https://github.com/caos/oidc/issues/145) to reflect more scenarios.

Hope I could help

**Comment by sebastiaopamplona** [comment] 2022-02-14 14:51
Hi @livio-a , thank you very much for taking the time to clarify the matter :) Have a nice day!

**Comment by livio-a** [comment] 2022-02-16 08:19
Ok I close this the PR as well as this issue (it is referenced in the documentation issue anyway)

Don't hesitate to contact me/us if you have any further problem or question.

**Closed by livio-a** 2022-02-16 08:19 UTC
Labels: bug
